### PR TITLE
Sweetalert2 instead of alert() function

### PR DESCRIPTION
**Pull request by hueychen27**
Sweetalert2 just looks better.

### CODE REVIEW

**Comment by Wriar** [comment]
Thanks for the PR, I'll review this change tomorrow.

**Comment by hueychen27** [comment]
ok

**Comment by hueychen27** [comment]
also forget about the add file and remove file changes. i forgot there were sweetalert2 cdns.

**Comment by Wriar** [comment]
LGTM!

**Comment by hueychen27** [comment]
yay

**Pull request merged**
